export const allItems = [
  // Tools & Equipment
  {
    id: 1,
    title: "DeWalt 20V Max Cordless Drill",
    description:
      "Professional-grade cordless drill with 2 batteries, charger, and carrying case. Perfect for any construction or DIY project.",
    price: 12.99,
    rating: 4.8,
    reviews: 24,
    image: "https://m.media-amazon.com/images/I/61m765U4UIL.jpg",
    category: "tools",
    categoryName: "Tools & Equipment",
    location: "Portland, OR",
    owner: "Mike Johnson",
    ownerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.9,
    ownerReviews: 42,
    features: ["Professional Grade", "2 Batteries Included", "Fast Charger", "Carrying Case"],
    available: true,
  },
  {
    id: 2,
    title: "Bosch Professional Angle Grinder",
    description:
      "High-performance 4.5-inch angle grinder with safety guard and extra cutting discs. Ideal for metal cutting and grinding.",
    price: 8.99,
    rating: 4.6,
    reviews: 18,
    image: "https://m.media-amazon.com/images/I/61TK8KolZ6L._AC_UF1000,1000_QL80_.jpg",
    category: "tools",
    categoryName: "Tools & Equipment",
    location: "Seattle, WA",
    owner: "David Wilson",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.7,
    ownerReviews: 28,
    features: ["Safety Guard", "Extra Discs", "Variable Speed", "Ergonomic Design"],
    available: true,
  },
  {
    id: 3,
    title: "Pressure Washer - 3000 PSI",
    description:
      "Electric pressure washer perfect for cleaning driveways, decks, cars, and outdoor furniture. Includes multiple nozzles.",
    price: 18.99,
    rating: 4.5,
    reviews: 31,
    image: "https://m.media-amazon.com/images/I/51VKnHL7bNL._AC_UF1000,1000_QL80_.jpg",
    category: "tools",
    categoryName: "Tools & Equipment",
    location: "Denver, CO",
    owner: "Sarah Martinez",
    ownerAvatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.8,
    ownerReviews: 35,
    features: ["3000 PSI Power", "Multiple Nozzles", "Electric Motor", "Compact Design"],
    available: true,
  },

  // Electronics
  {
    id: 4,
    title: "Canon EOS R5 Mirrorless Camera",
    description:
      "Professional 45MP full-frame mirrorless camera with 24-105mm lens. Includes extra batteries, memory cards, and camera bag.",
    price: 89.99,
    rating: 4.9,
    reviews: 15,
    image: "https://m.media-amazon.com/images/I/8115pNkutkL._AC_UF1000,1000_QL80_.jpg",
    category: "electronics",
    categoryName: "Electronics",
    location: "Seattle, WA",
    owner: "Sarah Chen",
    ownerAvatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.9,
    ownerReviews: 67,
    features: ["45MP Full Frame", "4K Video", "Image Stabilization", "Weather Sealed"],
    available: true,
  },
  {
    id: 5,
    title: "MacBook Pro 16-inch M2",
    description:
      "Latest MacBook Pro with M2 Max chip, 32GB RAM, and 1TB SSD. Perfect for video editing, design work, and development.",
    price: 75.99,
    rating: 4.8,
    reviews: 22,
    image: "https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=400&h=300&fit=crop",
    category: "electronics",
    categoryName: "Electronics",
    location: "San Francisco, CA",
    owner: "Alex Thompson",
    ownerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.9,
    ownerReviews: 45,
    features: ["M2 Max Chip", "32GB RAM", "1TB SSD", "16-inch Display"],
    available: true,
  },
  {
    id: 6,
    title: "Pioneer DJ DDJ-SX3 Controller",
    description:
      "Professional 4-channel DJ controller with Serato DJ Pro software. Includes speakers, microphone, and all cables.",
    price: 65.99,
    rating: 4.6,
    reviews: 19,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlOxB06lAPwJlvpSk38EjO-ZArIcbVtR7mpg&s",
    category: "electronics",
    categoryName: "Electronics",
    location: "Austin, TX",
    owner: "David Park",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.7,
    ownerReviews: 33,
    features: ["4-Channel Mixer", "Serato DJ Pro", "Built-in Effects", "Performance Pads"],
    available: true,
  },

  // Outdoor Gear
  {
    id: 7,
    title: "REI Co-op Base Camp 6 Tent",
    description:
      "Spacious 6-person tent with vestibule, waterproof and easy setup. Perfect for family camping trips and festivals.",
    price: 25.99,
    rating: 4.7,
    reviews: 28,
    image: "https://www.rei.com/media/ab2b84ab-7e81-4bcd-9103-ef3385d244f6.jpg?size=784x588",
    category: "outdoor",
    categoryName: "Outdoor Gear",
    location: "Denver, CO",
    owner: "Emily Rodriguez",
    ownerAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.8,
    ownerReviews: 52,
    features: ["6-Person Capacity", "Waterproof", "Easy Setup", "Large Vestibule"],
    available: true,
  },
  {
    id: 8,
    title: "Patagonia Sleeping Bag -10°F",
    description:
      "High-quality down sleeping bag rated for -10°F. Lightweight, compressible, and perfect for winter camping.",
    price: 15.99,
    rating: 4.8,
    reviews: 16,
    image: "https://i.ytimg.com/vi/W6EDgYB255Q/maxresdefault.jpg",
    category: "outdoor",
    categoryName: "Outdoor Gear",
    location: "Boulder, CO",
    owner: "Jake Miller",
    ownerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.9,
    ownerReviews: 38,
    features: ["Down Insulation", "-10°F Rating", "Lightweight", "Compressible"],
    available: true,
  },
  {
    id: 9,
    title: "Osprey Backpack 65L",
    description:
      "Professional hiking backpack with 65L capacity, rain cover, and multiple compartments. Perfect for multi-day hikes.",
    price: 12.99,
    rating: 4.6,
    reviews: 21,
    image: "https://m.media-amazon.com/images/I/61DB4HvcVKL._AC_UY1100_.jpg",
    category: "outdoor",
    categoryName: "Outdoor Gear",
    location: "Portland, OR",
    owner: "Lisa Chang",
    ownerAvatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.7,
    ownerReviews: 29,
    features: ["65L Capacity", "Rain Cover", "Multiple Compartments", "Adjustable Straps"],
    available: true,
  },

  // Photography
  {
    id: 10,
    title: "Sony A7R V Camera Body",
    description:
      "Professional 61MP full-frame mirrorless camera with advanced autofocus and 8K video recording capabilities.",
    price: 95.99,
    rating: 4.9,
    reviews: 12,
    image: "https://m.media-amazon.com/images/I/71qre0hvi6L._AC_UF1000,1000_QL80_.jpg",
    category: "photography",
    categoryName: "Photography",
    location: "Los Angeles, CA",
    owner: "Michael Chen",
    ownerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.9,
    ownerReviews: 78,
    features: ["61MP Sensor", "8K Video", "Advanced AF", "Image Stabilization"],
    available: true,
  },
  {
    id: 11,
    title: "Profoto B1X Flash Kit",
    description:
      "Professional studio flash kit with 2 lights, softboxes, stands, and wireless triggers. Perfect for portrait photography.",
    price: 55.99,
    rating: 4.8,
    reviews: 14,
    image: "https://images-cdn.ubuy.co.in/635d5b832aed31678c4b7bea-profoto-b1x-500-airttl-location-kit.jpg",
    category: "photography",
    categoryName: "Photography",
    location: "New York, NY",
    owner: "Rachel Green",
    ownerAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.8,
    ownerReviews: 41,
    features: ["2 Flash Heads", "Wireless Triggers", "Softboxes", "Light Stands"],
    available: true,
  },

  // Sports Equipment
  {
    id: 12,
    title: "Trek Mountain Bike - Full Suspension",
    description:
      "High-end mountain bike with full suspension, 29-inch wheels, and 12-speed drivetrain. Perfect for trail riding.",
    price: 35.99,
    rating: 4.7,
    reviews: 26,
    image: "https://www.sefiles.net/merchant/1912/images/site/trek-top-fuel-9.7-398588-1.jpg",
    category: "sports",
    categoryName: "Sports Equipment",
    location: "Boulder, CO",
    owner: "Tom Wilson",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.6,
    ownerReviews: 34,
    features: ["Full Suspension", "29-inch Wheels", "12-Speed", "Carbon Frame"],
    available: true,
  },
  {
    id: 13,
    title: "Surfboard - 9ft Longboard",
    description: "Classic longboard surfboard perfect for beginners and experienced surfers. Includes leash and wax.",
    price: 22.99,
    rating: 4.5,
    reviews: 18,
    image: "https://www.piransurf.co.uk/wp-content/uploads/2020/12/IMG_3104-scaled.jpeg",
    category: "sports",
    categoryName: "Sports Equipment",
    location: "San Diego, CA",
    owner: "Kelly Martinez",
    ownerAvatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.7,
    ownerReviews: 25,
    features: ["9ft Length", "Beginner Friendly", "Includes Leash", "Wax Included"],
    available: true,
  },

  // Furniture
  {
    id: 14,
    title: "Herman Miller Aeron Chair",
    description:
      "Ergonomic office chair with full adjustability and lumbar support. Perfect for home office or coworking space.",
    price: 28.99,
    rating: 4.8,
    reviews: 23,
    image: "https://m.media-amazon.com/images/I/71Quh+W6ACS._AC_UF1000,1000_QL80_.jpg",
    category: "furniture",
    categoryName: "Furniture",
    location: "Seattle, WA",
    owner: "Jennifer Lee",
    ownerAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.9,
    ownerReviews: 56,
    features: ["Ergonomic Design", "Lumbar Support", "Fully Adjustable", "Mesh Back"],
    available: true,
  },
  {
    id: 15,
    title: "IKEA Standing Desk - Electric",
    description:
      "Electric height-adjustable standing desk with memory presets. Great for improving posture and productivity.",
    price: 19.99,
    rating: 4.4,
    reviews: 17,
    image: "https://www.ikea.com/in/en/images/products/rodulf-desk-sit-stand-electric-white__1209823_pe909462_s5.jpg?f=m",
    category: "furniture",
    categoryName: "Furniture",
    location: "Portland, OR",
    owner: "Chris Johnson",
    ownerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.5,
    ownerReviews: 22,
    features: ["Electric Height Adjustment", "Memory Presets", "Large Surface", "Cable Management"],
    available: true,
  },

  // Vehicles
  {
    id: 16,
    title: "Tesla Model 3 - Long Range",
    description:
      "Electric vehicle with 350+ mile range, autopilot, and premium interior. Perfect for road trips and daily commuting.",
    price: 125.99,
    rating: 4.9,
    reviews: 31,
    image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400&h=300&fit=crop",
    category: "vehicles",
    categoryName: "Vehicles",
    location: "San Francisco, CA",
    owner: "Mark Davis",
    ownerAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.9,
    ownerReviews: 89,
    features: ["350+ Mile Range", "Autopilot", "Premium Interior", "Supercharger Access"],
    available: true,
  },
  {
    id: 17,
    title: "Honda CR-V - AWD SUV",
    description:
      "Reliable all-wheel-drive SUV with spacious interior and excellent fuel economy. Perfect for family trips.",
    price: 85.99,
    rating: 4.6,
    reviews: 28,
    image: "https://imgd.aeplcdn.com/1280x720/n/cw/ec/34457/cr-v-exterior-right-front-three-quarter.jpeg?q=80",
    category: "vehicles",
    categoryName: "Vehicles",
    location: "Denver, CO",
    owner: "Amanda Wilson",
    ownerAvatar: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.7,
    ownerReviews: 43,
    features: ["All-Wheel Drive", "Spacious Interior", "Great Fuel Economy", "Safety Features"],
    available: true,
  },

  // Party Supplies
  {
    id: 18,
    title: "Professional Sound System",
    description:
      "Complete PA system with speakers, mixer, microphones, and lighting. Perfect for parties, events, and presentations.",
    price: 45.99,
    rating: 4.7,
    reviews: 22,
    image: "https://www.jbl.com/dw/image/v2/BFND_PRD/on/demandware.static/-/Sites-siteCatalog_JB_US_Imported/default/dw4802104a/categoryimage/JBL_eComm_JBLPro_Category_Headers_PassivePA_800x400.jpg?sw=800&sh=400",
    category: "party",
    categoryName: "Party Supplies",
    location: "Austin, TX",
    owner: "Carlos Rodriguez",
    ownerAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.8,
    ownerReviews: 37,
    features: ["Professional Speakers", "Mixer Included", "Wireless Mics", "LED Lighting"],
    available: true,
  },
  {
    id: 19,
    title: "Inflatable Photo Booth",
    description:
      "Fun inflatable photo booth with props, backdrop, and instant camera. Great for weddings, parties, and events.",
    price: 32.99,
    rating: 4.5,
    reviews: 19,
    image: "https://partyhirehub.co.za/images/PhotoBooth/Party_Hire_Hub_Inflatable_Booth_Hire.jpg",
    category: "party",
    categoryName: "Party Supplies",
    location: "Miami, FL",
    owner: "Sofia Garcia",
    ownerAvatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    ownerRating: 4.6,
    ownerReviews: 28,
    features: ["Inflatable Design", "Props Included", "Instant Camera", "Easy Setup"],
    available: true,
  },
]

export const categories = [
  { name: "All Categories", slug: "all" },
  { name: "Tools & Equipment", slug: "tools" },
  { name: "Electronics", slug: "electronics" },
  { name: "Outdoor Gear", slug: "outdoor" },
  { name: "Photography", slug: "photography" },
  { name: "Sports Equipment", slug: "sports" },
  { name: "Furniture", slug: "furniture" },
  { name: "Vehicles", slug: "vehicles" },
  { name: "Party Supplies", slug: "party" },
]

export const priceRanges = [
  { label: "Under $20", min: 0, max: 20 },
  { label: "$20 - $50", min: 20, max: 50 },
  { label: "$50 - $100", min: 50, max: 100 },
  { label: "Over $100", min: 100, max: 1000 },
]

export const sortOptions = [
  { label: "Most Popular", value: "popular" },
  { label: "Price: Low to High", value: "price-asc" },
  { label: "Price: High to Low", value: "price-desc" },
  { label: "Highest Rated", value: "rating" },
  { label: "Newest", value: "newest" },
]
